@UserService_HostAddress = https://localhost:7207

POST {{UserService_HostAddress}}/api/users
Content-Type: application/json

{
  "UserName": "Bert"
}

###

@id=1
GET {{UserService_HostAddress}}/api/users/{{id}}

###
